### PR TITLE
Replace deprecated jsonpb package with protojson

### PR DESCRIPTION
**Pull request by ctlong**
Removes `github.com/golang/protobuf/jsonpb` dependency completely

### CODE REVIEW

**Comment by ctlong** [comment]
Need to run some integration tests to make sure this change is ok.

Pull it into one of the releases that use it (probably log-cache-release) and verify that stuff still works.

**Comment by ctlong** [comment]
🎉  Successfully ran unit tests in the log-cache-release with this PR pulled in:
```
cd log-cache-release/src
go get code.cloudfoundry.org/go-log-cache@e612c165be1345e085e3f7284fcf5ea2fba052f5
go mod vendor
go test -race ./...
# PASS
```

**Review by Benjamintf1 — APPROVED** [review]

**Comment by Benjamintf1** [comment]
my approval is contingent upon cats not failing with mis-matched protojson versions between lc and cf cli.

**Comment by ctlong** [comment]
🎉  A dev release of Log Cache that included this go-log-cache branch passed CATs

```
cd log-cache-release/src
go get code.cloudfoundry.org/go-log-cache@e612c165be1345e085e3f7284fcf5ea2fba052f5
go mod tidy
go mod vendor
bosh cr --force --tarball=/tmp/log-cache-release.tgz

# Upload the release to, and use it in, a CF-D environment
# Run CATs against that environment with the following config
echo '{
  "api": "api.infrared.cf-app.com",
  "admin_user": "admin",
  "apps_domain": "infrared.cf-app.com",
  "skip_ssl_validation": true,
  "use_http": true,
  "backend": "diego",
  "include_apps": true,
  "include_backend_compatibility": false,
  "include_container_networking": false,
  "include_detect": false,
  "include_docker": false,
  "include_internet_dependent": false,
  "include_privileged_container_support": false,
  "include_route_services": false,
  "include_routing": false,
  "include_security_groups": false,
  "include_services": false,
  "include_ssh": false,
  "include_sso": false,
  "include_tasks": false,
  "include_v3": false,
  "include_zipkin": false,
  "include_capi_experimental": false,
  "include_credhub": false,
  "include_isolation_segments": false,
  "include_routing_isolation_segments": false,
  "include_private_docker_registry": false,
  "isolation_segment_name": "persistent_isolation_segment",
  "credhub_client": "credhub_admin_client"
}' > config.json
```

**Pull request merged**
